elevation_mapping:
  ros__parameters:
 
    # GENERAL
    elevation_map_topic: "/elevation_map"
    map_frame_id: "odom"
    robot_base_frame_id: "base_link"
    sensor_frame_id: "vlp16"
    robot_odom_topic: "/odom"
    robot_odom_cache_size: 200
    robot_pose_with_covariance_topic: "base_link_pose"
    # LIDAR
    scanning_duration: 0.1
    input_sources: ["lidar"] # A name to identify the input source
    lidar:
      type: pointcloud # Supported types: pointcloud
      topic: /velodyne_points
      queue_size: 1
      publish_on_update: true # Whether to publish the elevation map after a callback from this source.
      sensor_processor:
          type: laser
          min_radius: 0.018
          beam_angle: 0.0006
          beam_constant: 0.0015
          ignore_points_above: 3.0
          ignore_points_below: -3.0
 
    # MAP ORIGIN
    track_point_frame_id: "base_link"
    track_point_x: 0.0
    track_point_y: 0.0
    track_point_z: -0.05  
 
    # MAP PARAMETERS
    length_in_x: 12.0
    length_in_y: 12.0
    resolution: 0.05   # in m/cell
    min_update_rate: 20.0
    min_variance: 0.000009
    max_variance: 0.01
    mahalanobis_distance_threshold: 2.5
    multi_height_noise: 0.0000009
 
    # MAP CLEANUP
    num_callback_threads: 5
    fused_map_publishing_rate: 20.0
    enable_visibility_cleanup: true
    visibility_cleanup_rate: 20.0
    enable_continuous_cleanup: false    # i.e. cleanup at every scan
