<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="scout">

    <xacro:arg name="robot_namespace" default="/" /> 
    <xacro:arg name="is_sim" default="true" />
    <xacro:arg name="laser_enabled" default="true" />

    <xacro:include filename="$(find scout_description)/urdf/scout_wheel_type1.xacro" />
    <xacro:include filename="$(find scout_description)/urdf/scout_wheel_type2.xacro" />
    <xacro:include filename="$(find scout_description)/urdf/scout_wheel_type3.xacro" />
    

    <!-- Variables -->
    <xacro:property name="M_PI" value="3.14159"/>

    <!-- Vehicle Geometries -->
    <xacro:property name="base_x_size" value="0.9250000" />
    <xacro:property name="base_y_size" value="0.380000" />
    <xacro:property name="base_z_size" value="0.210000" />

    <xacro:property name="wheelbase" value="0.498" />
    <xacro:property name="track" value="0.58306" />
    <xacro:property name="wheel_vertical_offset" value="-0.0702" />

    <xacro:property name="wheel_length" value="1.1653e-01" />
    <xacro:property name="wheel_radius" value="1.6459e-01" />

    <!-- Base link -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="file://$(find scout_description)/meshes/base_link.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0.008" rpy="0 0 0" />
            <geometry>
                <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
            </geometry>
        </collision>
        <collision>
            <origin xyz="0 0 ${base_z_size/6}" rpy="0 0 0" />
            <geometry>
                <box size="${base_x_size/6} ${base_y_size*1.65} ${base_z_size/3}"/>
            </geometry>
        </collision>
    </link>

    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${wheel_vertical_offset - wheel_radius}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="base_footprint" />
    </joint>

    <link name="inertial_link">
        <inertial>
            <mass value="40" />
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx="2.288641" ixy="0" ixz="0" iyy="5.103976" iyz="0" izz="3.431465" />
        </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint>

    <xacro:unless value="$(arg is_sim)">
        <xacro:scout_wheel_type1 wheel_prefix="front_right">
            <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="3.14 0 0" />
        </xacro:scout_wheel_type1>
        <xacro:scout_wheel_type2 wheel_prefix="front_left">
            <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
        </xacro:scout_wheel_type2>
        <xacro:scout_wheel_type1 wheel_prefix="rear_left">
            <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
        </xacro:scout_wheel_type1>
        <xacro:scout_wheel_type2 wheel_prefix="rear_right">
            <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="3.14 0 0" />
        </xacro:scout_wheel_type2>
    </xacro:unless>
    <xacro:if value="$(arg is_sim)">
        <xacro:scout_wheel_type3 wheel_prefix="front_right">
            <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
        </xacro:scout_wheel_type3>
        <xacro:scout_wheel_type3 wheel_prefix="front_left">
            <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
        </xacro:scout_wheel_type3>
        <xacro:scout_wheel_type3 wheel_prefix="rear_left">
            <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
        </xacro:scout_wheel_type3>
        <xacro:scout_wheel_type3 wheel_prefix="rear_right">
            <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
        </xacro:scout_wheel_type3>
    </xacro:if>


<xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro" />
<xacro:VLP-16 parent="vlp16_link" name="vlp16" tf_prefix="" topic="/velodyne_points" organize_cloud="false" hz="10" lasers="24" samples="940" collision_range="0.3" min_range="0.1" max_range="10.0" noise="0.008" min_angle="-${M_PI}" max_angle="${M_PI}" gpu="true">
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
</xacro:VLP-16>

<!-- Mount for VLP-16 LiDAR -->
<joint name="vlp16_mount_joint" type="fixed">
    <origin xyz="0.0 0.0 0.5" rpy="0 0 0"/> <!-- Adjust xyz and rpy as needed -->
    <parent link="base_link"/> <!-- Or another link, if more appropriate -->
    <child link="vlp16_link"/>
</joint>

<link name="vlp16_link">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <mesh filename="file://$(find velodyne_description)/meshes/VLP16_scan.dae" />
        </geometry>
    </visual>
</link>









    <xacro:if value="$(arg is_sim)">
        <xacro:include filename="$(find scout_description)/urdf/scout_gazebo.xacro" />    
        <xacro:gazebo_h2 prefix=""/> 
    </xacro:if>

</robot>
